spring:
  application:
    name: OnlineFoodDelivery
  datasource:
    url: jdbc:postgresql://localhost:5432/online_food_delivery_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
